apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: elk-logging
    node.name: ${HOSTNAME}
    discovery.type: single-node
    network.host: 0.0.0.0

    xpack.security.enabled: true
    xpack.security.autoconfiguration.enabled: false
    xpack.security.http.ssl.enabled: false
