apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: elk-logging
    node.name: ${HOSTNAME}
    discovery.type: single-node

    # Отключаем автоматическую настройку security
    xpack.security.enabled: false
    xpack.security.autoconfiguration.enabled: false
