apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.publicBaseUrl: "https://kibana.mycum.ru"

    elasticsearch.hosts: ["{{ .Values.elasticsearch.url }}"]

    # CSP-настройки
    csp.strict: false              # не блокировать браузер, если что-то не так
    csp.warnLegacyBrowsers: false  # не показывать попапы про "обновите браузер"
      
    xpack.security.enabled: false
