apiVersion: v2
name: logging-elk
description: Umbrella chart for ELK stack (Elasticsearch + Kibana + Fluent Bit)
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: elasticsearch
    version: 0.1.0
    repository: "file://../elasticsearch"

#  - name: kibana
#    version: 0.1.0
#    repository: "file://../kibana"
#
#  - name: fluent-bit
#    version: 0.1.0
#    repository: "file://../fluent-bit"
